version: "3.9"

services:
  keypoint:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: keypoint_container
    runtime: nvidia
    shm_size : '30gb'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
      - CONDA_DEFAULT_ENV=keyPoint
      - PATH=/opt/conda/envs/keyPoint/bin:$PATH
    volumes:
      - ./:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true

