name: keyPoint
channels:
  - anaconda
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _sysroot_linux-64_curr_repodata_hack=3
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - aom=3.6.0
  - appdirs=1.4.4
  - ase=3.23.0
  - atk-1.0=2.36.0
  - attrs=24.2.0
  - blas=1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - boost-cpp=1.82.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.9.24
  - cairo=1.16.0
  - captum=0.7.0
  - certifi=2024.8.30
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.2.0
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=9.3.0.75
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - docker-pycreds=0.4.0
  - easydict=1.13
  - expat=2.6.3
  - ffmpeg=4.3
  - filelock=3.13.1
  - flask=3.0.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freetype-py=2.3.0
  - fribidi=1.0.10
  - frozenlist=1.4.0
  - fsspec=2024.6.1
  - gdk-pixbuf=2.42.10
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gobject-introspection=1.78.1
  - graphite2=1.3.14
  - graphviz=2.50.0
  - greenlet=3.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gtk2=2.24.33
  - gts=0.7.6
  - h5py=3.11.0
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - intel-openmp=2023.1.0
  - isodate=0.6.1
  - itsdangerous=2.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jxrlib=1.1
  - kernel-headers_linux-64=3.10.0
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libavif=0.11.1
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-python=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.4.2
  - libcurand=10.3.5.147
  - libcurl=8.9.1
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmagma=2.8.0
  - libmagma_sparse=2.8.0
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - librsvg=2.54.4
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtool=2.4.6
  - libtorch=2.4.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.49.2
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.13.1
  - libzopfli=1.0.3
  - lightning-utilities=0.9.0
  - llvm-openmp=19.1.3
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mkl=2023.2.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.10
  - mkl_random=1.2.7
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - multidict=6.0.4
  - mysql=5.7.24
  - nccl=2.23.4.1
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.2.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.35
  - nss=3.89.1
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - opt_einsum=3.3.0
  - packaging=24.1
  - pandas=2.2.2
  - pango=1.50.7
  - patsy=0.5.6
  - pcre2=10.42
  - pgmpy=0.1.24
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - poppler=24.09.0
  - poppler-data=0.4.11
  - protobuf=4.25.3
  - psutil=5.9.0
  - pybind11-abi=4
  - pycairo=1.23.0
  - pynndescent=0.5.10
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytorch_geometric=2.6.1
  - pytorch_spline_conv=1.2.2
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.2
  - rdflib=7.0.0
  - rdkit=2023.03.3
  - readline=8.2
  - reportlab=4.2.5
  - requests=2.32.3
  - rlpycairo=0.2.0
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - sentry-sdk=2.18.0
  - setproctitle=1.2.2
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sleef=3.7
  - smmap=4.0.0
  - snappy=1.2.1
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - statsmodels=0.14.2
  - sympy=1.13.2
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tifffile=2023.4.12
  - tk=8.6.14
  - torch-scatter=2.1.1
  - torchaudio=2.4.1
  - torchmetrics=1.4.0.post0
  - torchtriton=3.1.0
  - torchvision=0.15.2
  - tornado=6.4.1
  - tqdm=4.66.5
  - trimesh=4.4.9
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wandb=0.18.7
  - werkzeug=3.0.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.11.0
  - zfp=1.0.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - albucore==0.0.23
      - albumentations==2.0.5
      - annotated-types==0.7.0
      - einops==0.8.0
      - huggingface-hub==0.29.1
      - opencv-python-headless==4.11.0.86
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - rotary-embedding-torch==0.8.6
      - safetensors==0.5.2
      - simsimd==6.2.1
      - stringzilla==3.12.2
      - timm==1.0.14
      - typing-extensions==4.12.2
